/**
 * End-to-end integration tests: afterTask → storage → beforeSpawn closed loop.
 * Verifies the full self-learning pipeline: signal resolution → reflection generation
 * → persistence → BM25 retrieval → injection.
 *
 * Source modules under test:
 *   - src/hooks/index.ts (handleAfterTask, handleBeforeSpawn)
 *   - src/reflection/index.ts (generateReflection, retrieveReflections)
 *   - src/storage/facade.ts + repository.ts
 *   - src/search/index.ts
 *
 * Design refs:
 *   - business_rules[reflection-generation-on-task-complete]
 *   - business_rules[reflection-injection-on-spawn]
 *   - endpoints[hook-after-task]
 *   - endpoints[hook-before-spawn]
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { initializeDatabase } from '../../src/storage/db.js';
import { createSearchEngine } from '../../src/search/index.js';
import { StorageFacade } from '../../src/storage/facade.js';
import { handleAfterTask, handleBeforeSpawn } from '../../src/hooks/index.js';
import * as reflectionModule from '../../src/reflection/index.js';
import type { DB } from '../../src/storage/db.js';
import type { Message, TaskSignals, ReflectionEntry } from '../../src/types/index.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTempDbPath(): string {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'learnloop-e2e-loop-test-'));
  return path.join(tmpDir, 'test.db');
}

function makeConversationHistory(): Message[] {
  return [
    { role: 'user', content: 'Implement the feature.' },
    { role: 'assistant', content: 'The feature has been implemented.' },
  ];
}

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

let db: DB;
let tempDbPath: string;
let facade: StorageFacade;

beforeEach(() => {
  tempDbPath = makeTempDbPath();
  db = initializeDatabase(tempDbPath);
  const engine = createSearchEngine(db);
  facade = new StorageFacade(db, engine);
});

afterEach(() => {
  vi.restoreAllMocks();
  try { db.close(); } catch { /* ignore */ }
  try {
    fs.rmSync(path.dirname(tempDbPath), { recursive: true, force: true });
  } catch { /* ignore */ }
});

// ---------------------------------------------------------------------------
// AC1: afterTask-generated reflection is retrieved by beforeSpawn (full loop)
// ---------------------------------------------------------------------------

describe('E2E reflection loop: afterTask generates → beforeSpawn injects (AC1)', () => {
  it('reflection generated by afterTask is retrieved and injected by subsequent beforeSpawn (AC1)', async () => {
    // GIVEN: empty DB, LLM mock returns a known reflection
    const reflectionText = 'The code feature was implemented using TDD. Tests were written first.';
    const lessonText = 'Always write unit tests before implementation';

    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: '实现代码功能',
      outcome: 'success',
      reflection: reflectionText,
      lessons: [lessonText],
    });

    // WHEN: Task A completes — afterTask hook fires with task_type='code'
    const afterTaskResult = await handleAfterTask(db, facade, {
      session_key: 'session-task-a',
      task_type: 'code',
      task_summary: '实现代码功能',
      conversation_history: makeConversationHistory(),
      signals: {
        user_feedback: 'wrong',
        review_result: null,
        was_respawned: false,
        timed_out: false,
      },
      agent_id: null,
    });

    // Wait for async DB write to complete
    await new Promise(r => setTimeout(r, 100));

    // Verify the reflection was generated and stored
    expect(afterTaskResult.reflection_id).not.toBeNull();
    const storedReflections = db
      .prepare('SELECT * FROM reflections')
      .all() as ReflectionEntry[];
    expect(storedReflections.length).toBe(1);
    expect(storedReflections[0].id).toBe(afterTaskResult.reflection_id);

    // AND: Task B is about to spawn — beforeSpawn hook fires with task_type='code'
    const beforeSpawnResult = await handleBeforeSpawn(db, facade, {
      task_description: '实现代码功能模块',
      task_type: 'code',
      agent_id: null,
    });

    // THEN: beforeSpawn retrieved and injected the reflection from Task A
    expect(beforeSpawnResult.injected_reflections.length).toBeGreaterThan(0);

    // Verify the injection contains the reflection generated by afterTask
    const injectedIds = beforeSpawnResult.injected_reflections.map(r => r.id);
    expect(injectedIds).toContain(afterTaskResult.reflection_id);
  });

  it('beforeSpawn injected_reflections includes reflection generated by afterTask (AC1)', async () => {
    // Arrange: afterTask generates a reflection
    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: 'implement login feature',
      outcome: 'failure',
      reflection: 'Login implementation failed due to missing error handling.',
      lessons: ['Always handle edge cases', 'Test authentication flows'],
    });

    await handleAfterTask(db, facade, {
      session_key: 'session-a',
      task_type: 'code',
      task_summary: 'implement login feature',
      conversation_history: makeConversationHistory(),
      signals: { user_feedback: 'wrong', review_result: null, was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    // Act: beforeSpawn fires for a related code task
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement user login',
      task_type: 'code',
      agent_id: null,
    });

    // Assert: injection happened
    expect(result.injected_reflections.length).toBeGreaterThan(0);
    expect(result.augmented_task_description.length).toBeGreaterThan('implement user login'.length);
    expect(result.augmented_task_description).toContain('implement user login');
  });
});

// ---------------------------------------------------------------------------
// AC2: Injected content matches original reflection content (reflection + lessons)
// ---------------------------------------------------------------------------

describe('E2E reflection loop: injected content consistency with original (AC2)', () => {
  it('injected reflection text exactly matches the reflection generated by afterTask (AC2)', async () => {
    const reflectionText = 'The deployment failed because environment variables were missing in production.';
    const lessonText = 'Always verify env vars before deploying to prod';

    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'deployment',
      task_summary: 'deploy api to production',
      outcome: 'failure',
      reflection: reflectionText,
      lessons: [lessonText],
    });

    await handleAfterTask(db, facade, {
      session_key: 'session-deploy-a',
      task_type: 'deployment',
      task_summary: 'deploy api to production',
      conversation_history: [],
      signals: { user_feedback: null, review_result: 'FAIL', was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    // beforeSpawn for a related deployment task
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'deploy api to production environment',
      task_type: 'deployment',
      agent_id: null,
    });

    expect(result.injected_reflections.length).toBeGreaterThan(0);

    const injected = result.injected_reflections[0];

    // Reflection text must match exactly (AC2)
    expect(injected.reflection).toBe(reflectionText);
  });

  it('injected lessons array contains the same lessons as generated by afterTask (AC2)', async () => {
    const lessons = ['Use TDD methodology', 'Always review before merge', 'Keep PRs small'];

    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: 'code review implementation',
      outcome: 'success',
      reflection: 'Code review completed with minor issues.',
      lessons,
    });

    await handleAfterTask(db, facade, {
      session_key: 'session-review-a',
      task_type: 'code',
      task_summary: 'code review implementation',
      conversation_history: [],
      signals: { user_feedback: 'thanks', review_result: null, was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement code review process',
      task_type: 'code',
      agent_id: null,
    });

    expect(result.injected_reflections.length).toBeGreaterThan(0);
    const injected = result.injected_reflections[0];

    // Lessons must be a parsed array (not JSON string) in injection result
    expect(Array.isArray(injected.lessons)).toBe(true);
    // Lessons must contain the same content as generated
    for (const lesson of lessons) {
      expect(injected.lessons).toContain(lesson);
    }
  });

  it('augmented_task_description contains lessons text from afterTask-generated reflection (AC2)', async () => {
    const uniqueLesson = 'unique-lesson-text-abc123-for-testing';

    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: 'implement test feature',
      outcome: 'success',
      reflection: 'Feature completed.',
      lessons: [uniqueLesson],
    });

    await handleAfterTask(db, facade, {
      session_key: 'session-lesson-test',
      task_type: 'code',
      task_summary: 'implement test feature',
      conversation_history: [],
      signals: { user_feedback: 'good', review_result: null, was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement test feature again',
      task_type: 'code',
      agent_id: null,
    });

    expect(result.injected_reflections.length).toBeGreaterThan(0);
    // The unique lesson text must appear in the augmented description (AC2)
    expect(result.augmented_task_description).toContain(uniqueLesson);
  });
});

// ---------------------------------------------------------------------------
// AC3: Reflections from different task_type are not injected into unrelated tasks
// ---------------------------------------------------------------------------

describe('E2E reflection loop: task_type isolation — no cross-type injection (AC3)', () => {
  it('reflection stored with task_type=research is not injected for task_type=deployment (AC3)', async () => {
    // GIVEN: a reflection exists for task_type='research'
    const researchReflection: ReflectionEntry = {
      id: 'research-r1',
      task_type: 'research',
      task_summary: 'research machine learning papers about transformers',
      outcome: 'success',
      signals: '{}',
      reflection: 'Found 10 relevant papers on transformer architectures.',
      lessons: '["Read paper abstracts first", "Filter by citation count"]',
      agent_id: null,
      source_session: 'session-research',
      created_at: new Date().toISOString(),
    };
    facade.addReflection(researchReflection);

    // WHEN: beforeSpawn fires for task_type='deployment' with deployment-specific query
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'deploy application to kubernetes cluster in production',
      task_type: 'deployment',
      agent_id: null,
    });

    // THEN: the research reflection should NOT be injected (no semantic overlap)
    const injectedIds = result.injected_reflections.map(r => r.id);
    expect(injectedIds).not.toContain('research-r1');

    // Verify the research-specific lesson text is NOT in the augmented description
    expect(result.augmented_task_description).not.toContain('Read paper abstracts first');
    expect(result.augmented_task_description).not.toContain('Filter by citation count');
  });

  it('only code reflections appear in code task injection (AC3)', async () => {
    // GIVEN: reflections for 'research' and 'design' task types exist
    facade.addReflection({
      id: 'r-research',
      task_type: 'research',
      task_summary: 'research api documentation standards',
      outcome: 'success',
      signals: '{}',
      reflection: 'Researched REST API documentation standards.',
      lessons: '["Use OpenAPI spec"]',
      agent_id: null,
      source_session: 's-research',
      created_at: new Date().toISOString(),
    });
    facade.addReflection({
      id: 'r-design',
      task_type: 'design',
      task_summary: 'design system architecture diagrams',
      outcome: 'success',
      signals: '{}',
      reflection: 'Designed the system architecture.',
      lessons: '["Draw architecture first"]',
      agent_id: null,
      source_session: 's-design',
      created_at: new Date().toISOString(),
    });
    // AND: a code reflection also exists
    facade.addReflection({
      id: 'r-code',
      task_type: 'code',
      task_summary: 'implement user authentication code',
      outcome: 'success',
      signals: '{}',
      reflection: 'Authentication code was implemented with JWT.',
      lessons: '["Use secure JWT libraries"]',
      agent_id: null,
      source_session: 's-code',
      created_at: new Date().toISOString(),
    });

    // WHEN: beforeSpawn fires for task_type='code'
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement user authentication',
      task_type: 'code',
      agent_id: null,
    });

    // THEN: if any reflections are injected, they should be from the code type
    if (result.injected_reflections.length > 0) {
      const injectedIds = result.injected_reflections.map(r => r.id);
      // code reflection should be among injected
      expect(injectedIds).toContain('r-code');
    }

    // research-specific and design-specific lessons should not appear
    // unless BM25 ranked them (task description overlaps), but given
    // completely different domains, they should be absent
    expect(result.augmented_task_description).not.toContain('Draw architecture first');
  });

  it('BDD Scenario 2: research reflection not injected into deployment task (AC3)', async () => {
    // BDD: GIVEN stored task_type='research' reflection
    // WHEN: beforeSpawn called with task_type='deployment'
    // THEN: research reflection NOT in injected_reflections

    const researchReflection: ReflectionEntry = {
      id: 'bdd2-research',
      task_type: 'research',
      task_summary: 'analyze academic research papers',
      outcome: 'partial',
      signals: '{}',
      reflection: 'Analyzed 50 academic papers on machine learning.',
      lessons: '["Use citation databases", "Focus on recent publications"]',
      agent_id: null,
      source_session: 'session-bdd2',
      created_at: new Date().toISOString(),
    };
    facade.addReflection(researchReflection);

    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'deploy containerized application to cloud infrastructure',
      task_type: 'deployment',
      agent_id: null,
    });

    // research reflections must not be injected into deployment tasks
    const injectedIds = result.injected_reflections.map(r => r.id);
    expect(injectedIds).not.toContain('bdd2-research');
  });
});

// ---------------------------------------------------------------------------
// AC4: Multiple reflections from multiple afterTask completions are sorted by BM25
// ---------------------------------------------------------------------------

describe('E2E reflection loop: multiple afterTask completions → BM25-sorted injection (AC4)', () => {
  it('multiple reflections stored in sequence are all retrievable and sorted by relevance (AC4)', async () => {
    // GIVEN: Three different task completions for 'code' task type with varying relevance
    const reflectionResponses = [
      {
        task_type: 'code',
        task_summary: 'implement user authentication login',
        outcome: 'success' as const,
        reflection: 'User authentication was implemented using JWT with secure token storage.',
        lessons: ['Use secure JWT libraries', 'Store tokens in httpOnly cookies'],
      },
      {
        task_type: 'code',
        task_summary: 'implement code review workflow',
        outcome: 'partial' as const,
        reflection: 'Code review workflow was partially set up with some gaps in automation.',
        lessons: ['Automate code review checks', 'Set clear review criteria'],
      },
      {
        task_type: 'code',
        task_summary: 'implement database migration scripts',
        outcome: 'failure' as const,
        reflection: 'Database migration failed due to schema conflicts.',
        lessons: ['Test migrations in staging first', 'Keep migration scripts idempotent'],
      },
    ];

    // Complete three tasks in sequence
    for (const resp of reflectionResponses) {
      vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValueOnce(resp);

      await handleAfterTask(db, facade, {
        session_key: `session-${resp.task_summary.slice(0, 10)}`,
        task_type: resp.task_type,
        task_summary: resp.task_summary,
        conversation_history: makeConversationHistory(),
        signals: { user_feedback: null, review_result: null, was_respawned: false, timed_out: false },
        agent_id: null,
      });

      // Wait for each async DB write
      await new Promise(r => setTimeout(r, 100));
    }

    // Verify all 3 reflections are stored
    const storedCount = db
      .prepare('SELECT COUNT(*) as cnt FROM reflections')
      .get() as { cnt: number };
    expect(storedCount.cnt).toBe(3);

    // WHEN: beforeSpawn fires for a login-related code task
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement login authentication system',
      task_type: 'code',
      agent_id: null,
    });

    // THEN: injection happened
    expect(result.injected_reflections.length).toBeGreaterThan(0);

    // AND: results are sorted by BM25 score descending (AC4)
    for (let i = 1; i < result.injected_reflections.length; i++) {
      expect(result.injected_reflections[i - 1].score).toBeGreaterThanOrEqual(
        result.injected_reflections[i].score,
      );
    }
  });

  it('BM25 returns most relevant reflection first when multiple stored (AC4)', async () => {
    // Insert two reflections: one highly relevant to "authentication", one about "database"
    const now = new Date().toISOString();
    facade.addReflection({
      id: 'auth-reflection',
      task_type: 'code',
      task_summary: 'implement authentication login JWT token',
      outcome: 'success',
      signals: '{}',
      reflection: 'Authentication was implemented with JWT tokens and login was secured.',
      lessons: '["Use JWT for authentication"]',
      agent_id: null,
      source_session: 's-auth',
      created_at: now,
    });
    facade.addReflection({
      id: 'db-reflection',
      task_type: 'code',
      task_summary: 'implement database schema migration',
      outcome: 'failure',
      signals: '{}',
      reflection: 'Database migration had schema conflicts causing failures.',
      lessons: '["Test migrations in staging"]',
      agent_id: null,
      source_session: 's-db',
      created_at: now,
    });

    // WHEN: beforeSpawn with login-related task description
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement JWT authentication token login',
      task_type: 'code',
      agent_id: null,
    });

    expect(result.injected_reflections.length).toBeGreaterThan(0);

    // BM25 ordering: auth-reflection should rank higher than db-reflection
    // because it has more keyword overlap with the query
    if (result.injected_reflections.length >= 2) {
      // Verify sort order: scores are descending
      for (let i = 1; i < result.injected_reflections.length; i++) {
        expect(result.injected_reflections[i - 1].score).toBeGreaterThanOrEqual(
          result.injected_reflections[i].score,
        );
      }
      // The most relevant reflection should be auth-related
      expect(result.injected_reflections[0].id).toBe('auth-reflection');
    } else {
      // At least one injection happened
      expect(result.injected_reflections[0].id).toBe('auth-reflection');
    }
  });

  it('afterTask writing multiple reflections then beforeSpawn respects the injection limit (AC4)', async () => {
    // GIVEN: 8 reflections stored for task_type='code' (exceeds default limit of 5)
    for (let i = 0; i < 8; i++) {
      vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValueOnce({
        task_type: 'code',
        task_summary: `implement feature module ${i}`,
        outcome: 'success',
        reflection: `Feature module ${i} was implemented successfully with tests.`,
        lessons: [`Lesson from task ${i}`],
      });

      await handleAfterTask(db, facade, {
        session_key: `session-limit-${i}`,
        task_type: 'code',
        task_summary: `implement feature module ${i}`,
        conversation_history: [],
        signals: { user_feedback: 'good', review_result: null, was_respawned: false, timed_out: false },
        agent_id: null,
      });

      await new Promise(r => setTimeout(r, 50));
    }

    // Verify 8 reflections are in DB
    const cnt = db.prepare('SELECT COUNT(*) as c FROM reflections').get() as { c: number };
    expect(cnt.c).toBe(8);

    // WHEN: beforeSpawn fires (default limit = 5)
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement feature module code',
      task_type: 'code',
      agent_id: null,
    });

    // THEN: at most 5 injected (default reflectionInjectionLimit = 5)
    expect(result.injected_reflections.length).toBeLessThanOrEqual(5);
  });
});

// ---------------------------------------------------------------------------
// Full data flow integrity: signal → outcome → reflection text → storage → retrieval
// ---------------------------------------------------------------------------

describe('E2E reflection loop: full data flow integrity (signal → outcome → storage → injection)', () => {
  it('outcome resolved from signals is stored correctly and accessible via beforeSpawn injection (AC1, AC2)', async () => {
    // Signals: user_feedback='wrong' → outcome='failure'
    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: 'implement data processing pipeline',
      outcome: 'failure',
      reflection: 'Data processing pipeline had critical bugs in error handling.',
      lessons: ['Handle exceptions at each pipeline stage'],
    });

    await handleAfterTask(db, facade, {
      session_key: 'session-signal-test',
      task_type: 'code',
      task_summary: 'implement data processing pipeline',
      conversation_history: [],
      signals: { user_feedback: 'wrong', review_result: null, was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    // Verify DB stores the correct outcome
    const storedRows = db
      .prepare('SELECT outcome FROM reflections')
      .all() as Array<{ outcome: string }>;
    expect(storedRows.length).toBe(1);
    expect(storedRows[0].outcome).toBe('failure');

    // Verify beforeSpawn retrieves and injects this reflection
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'implement data processing pipeline',
      task_type: 'code',
      agent_id: null,
    });

    expect(result.injected_reflections.length).toBeGreaterThan(0);
    // The injected reflection should have outcome='failure'
    expect(result.injected_reflections[0].outcome).toBe('failure');
  });

  it('reflection text flows intact from afterTask through storage to beforeSpawn injection (AC1, AC2)', async () => {
    const uniqueReflectionText = 'reflection-content-unique-xyz789-testing-flow';

    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: 'flow test task summary',
      outcome: 'partial',
      reflection: uniqueReflectionText,
      lessons: ['lesson from flow test'],
    });

    await handleAfterTask(db, facade, {
      session_key: 'session-flow-test',
      task_type: 'code',
      task_summary: 'flow test task summary',
      conversation_history: [],
      signals: { user_feedback: null, review_result: null, was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    // Verify it's in the DB
    const stored = db
      .prepare('SELECT reflection FROM reflections')
      .all() as Array<{ reflection: string }>;
    expect(stored.length).toBe(1);
    expect(stored[0].reflection).toBe(uniqueReflectionText);

    // Verify beforeSpawn returns it in injected_reflections
    const result = await handleBeforeSpawn(db, facade, {
      task_description: 'flow test task execution',
      task_type: 'code',
      agent_id: null,
    });

    expect(result.injected_reflections.length).toBeGreaterThan(0);
    expect(result.injected_reflections[0].reflection).toBe(uniqueReflectionText);

    // And the augmented description contains it too
    expect(result.augmented_task_description).toContain(uniqueReflectionText);
  });

  it('beforeSpawn returns original task_description unchanged when afterTask generated nothing (silent degradation)', async () => {
    // afterTask LLM fails → no reflection stored
    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue(null);

    await handleAfterTask(db, facade, {
      session_key: 'session-no-reflection',
      task_type: 'code',
      task_summary: 'implement some feature',
      conversation_history: [],
      signals: { user_feedback: 'thanks', review_result: null, was_respawned: false, timed_out: false },
      agent_id: null,
    });

    await new Promise(r => setTimeout(r, 100));

    // Verify no reflections in DB
    const cnt = db.prepare('SELECT COUNT(*) as c FROM reflections').get() as { c: number };
    expect(cnt.c).toBe(0);

    // beforeSpawn should return original task description unchanged
    const originalDescription = 'implement some code feature';
    const result = await handleBeforeSpawn(db, facade, {
      task_description: originalDescription,
      task_type: 'code',
      agent_id: null,
    });

    expect(result.augmented_task_description).toBe(originalDescription);
    expect(result.injected_reflections).toEqual([]);
  });

  it('BDD Scenario 1: complete afterTask→beforeSpawn loop with negative user_feedback (wrong)', async () => {
    // BDD Scenario 1:
    // GIVEN: empty storage
    // WHEN: afterTask called with task_type='code', user_feedback='wrong'
    // THEN: afterTask generates reflection, stores it
    // WHEN: beforeSpawn called with task_type='code'
    // THEN: beforeSpawn retrieves and injects the stored reflection

    const knownReflection = 'implementation failed due to incorrect error handling logic';
    const knownLesson = 'validate all error paths before finalizing implementation';

    vi.spyOn(reflectionModule, 'generateReflection').mockResolvedValue({
      task_type: 'code',
      task_summary: 'implement error handler',
      outcome: 'failure',
      reflection: knownReflection,
      lessons: [knownLesson],
    });

    const afterTaskResult = await handleAfterTask(db, facade, {
      session_key: 'bdd1-session-a',
      task_type: 'code',
      task_summary: 'implement error handler',
      conversation_history: makeConversationHistory(),
      signals: {
        user_feedback: 'wrong',
        review_result: null,
        was_respawned: false,
        timed_out: false,
      },
      agent_id: null,
    });

    // afterTask returns a valid reflection_id
    expect(afterTaskResult.reflection_id).not.toBeNull();
    expect(afterTaskResult.outcome).toBe('failure');

    // Wait for async DB write
    await new Promise(r => setTimeout(r, 100));

    // Confirm stored
    const storedEntry = db
      .prepare('SELECT * FROM reflections WHERE id = ?')
      .get(afterTaskResult.reflection_id) as ReflectionEntry;
    expect(storedEntry).toBeDefined();
    expect(storedEntry.reflection).toBe(knownReflection);

    // beforeSpawn injects the stored reflection
    const beforeSpawnResult = await handleBeforeSpawn(db, facade, {
      task_description: 'implement error handler code',
      task_type: 'code',
      agent_id: null,
    });

    // AC1: the reflection generated by afterTask is retrieved by beforeSpawn
    const injectedIds = beforeSpawnResult.injected_reflections.map(r => r.id);
    expect(injectedIds).toContain(afterTaskResult.reflection_id);

    // AC2: injected content matches original
    const injectedEntry = beforeSpawnResult.injected_reflections.find(
      r => r.id === afterTaskResult.reflection_id,
    );
    expect(injectedEntry).toBeDefined();
    expect(injectedEntry!.reflection).toBe(knownReflection);
    expect(injectedEntry!.lessons).toContain(knownLesson);

    // augmented_task_description contains lesson text
    expect(beforeSpawnResult.augmented_task_description).toContain(knownLesson);
  });
});
